import { type Archetype } from "@/lib/personalities/archetypes";
import {
  PAGE_KINDS,
  profileKindUsesIdentity,
  type PageKind,
} from "@/lib/avatars/page-kind";
import {
  getArchetypesForPageKind,
  pageKindUsesArchetype,
} from "@/lib/personalities/kind-archetypes";
import {
  GENDERS,
  defaultPronounsForGender,
  isFeminineGender,
  isMasculineGender,
  type Gender,
} from "@/lib/personalities/gender";
import { PRONOUNS, type Pronouns } from "@/lib/personalities/pronouns";
import { randomPoliticalSwing } from "@/lib/personalities/political-swing";
import type { PoliticalSwing } from "@/lib/personalities/political-swing";
import { slugifyHandle } from "@/lib/personalities/validation";
import type { Traits } from "@/lib/types/personality";

const MALE_FIRST_NAMES = [
  "Marcus",
  "Leo",
  "Omar",
  "Felix",
  "Victor",
  "Amir",
  "Diego",
  "Luca",
  "Theo",
  "Ivan",
  "Miles",
  "Jonah",
  "Silas",
  "Hugo",
  "Noah",
  "Logan",
  "Ethan",
  "Adrian",
  "Julian",
  "Oscar",
  "Mateo",
  "Rafael",
  "Nico",
  "Andre",
  "Malik",
];

const FEMALE_FIRST_NAMES = [
  "Emma",
  "Luna",
  "Maya",
  "Zoe",
  "Nina",
  "Cleo",
  "Iris",
  "Ruby",
  "Jade",
  "Skye",
  "Elena",
  "Sofia",
  "Priya",
  "Hana",
  "Clara",
  "Naomi",
  "Tessa",
  "Vera",
  "Ines",
  "Amina",
  "Leila",
  "Camila",
  "Freya",
  "Isla",
  "Nadia",
];

const NEUTRAL_FIRST_NAMES = [
  "Alex",
  "Jordan",
  "Sam",
  "Riley",
  "Casey",
  "Morgan",
  "Quinn",
  "Avery",
  "Blake",
  "Drew",
  "Jamie",
  "Kai",
  "Ren",
  "Yuki",
  "Rowan",
  "Sage",
  "River",
  "Skyler",
  "Remy",
  "Ash",
];

const LAST_NAMES = [
  "Reed",
  "Shaw",
  "Blake",
  "Cross",
  "Vale",
  "Stone",
  "Fox",
  "Lane",
  "Marsh",
  "Wolf",
  "Knight",
  "Storm",
  "River",
  "Lake",
  "Brooks",
  "Hayes",
  "Cole",
  "West",
  "North",
  "Page",
  "Quinn",
  "Sato",
  "Chen",
  "Patel",
  "Silva",
  "Khan",
  "Rossi",
  "Nguyen",
  "Park",
  "Singh",
  "Morales",
  "Ortega",
  "Bauer",
  "Klein",
  "Novak",
  "Ibarra",
  "Santos",
  "Romero",
  "Fischer",
  "Weber",
  "Moreau",
  "Dupont",
  "Ali",
  "Hassan",
  "Okafor",
  "Mbeki",
  "Tanaka",
  "Yamamoto",
  "Kowalski",
  "Nowak",
];

const NAME_PARTS: Record<Archetype, { prefixes: string[]; suffixes: string[] }> =
  {
    comedian: {
      prefixes: [
        "Bit",
        "Meme",
        "Ratio",
        "Joke",
        "Punchline",
        "Dunk",
        "Roast",
        "Snark",
        "Gag",
        "Wit",
        "Clown",
        "Banter",
        "Satire",
        "Cursed",
        "Based",
        "Cringe",
        "Shitpost",
        "Viral",
        "Caption",
        "Comedy",
        "Laugh",
        "Irony",
        "Parody",
        "Sketch",
      ],
      suffixes: [
        "Bot",
        "Lord",
        "Machine",
        "Goblin",
        "Comedian",
        "King",
        "Queen",
        "Factory",
        "Wizard",
        "Gremlin",
        "Pilot",
        "Engine",
        "Merchant",
        "Bandit",
        "Saint",
        "Demon",
        "Intern",
        "Professor",
        "Captain",
        "Agent",
        "Supreme",
        "Overlord",
        "Champion",
        "Menace",
        "Legend",
      ],
    },
    journalist: {
      prefixes: [
        "Daily",
        "Breaking",
        "Wire",
        "Thread",
        "Source",
        "Front",
        "Night",
        "City",
        "Global",
        "Field",
        "Press",
        "Report",
        "Signal",
        "Dispatch",
        "Bulletin",
        "Ledger",
        "Chronicle",
        "Herald",
        "Anchor",
        "Scoop",
        "Leak",
        "Brief",
        "Desk",
        "Editor",
        "Correspondent",
      ],
      suffixes: [
        "Desk",
        "Report",
        "Herald",
        "Bulletin",
        "Scoop",
        "Wire",
        "Room",
        "Beat",
        "Post",
        "Times",
        "Observer",
        "Monitor",
        "Review",
        "Journal",
        "Network",
        "Channel",
        "Briefing",
        "Dispatch",
        "Ledger",
        "Archive",
        "Corps",
        "Bureau",
        "Press",
        "Anchor",
        "Source",
      ],
    },
    conspiracy: {
      prefixes: [
        "Red",
        "Truth",
        "Signal",
        "Deep",
        "Hidden",
        "Shadow",
        "Black",
        "Void",
        "Cipher",
        "Echo",
        "Static",
        "Parallax",
        "Quantum",
        "Fractal",
        "Midnight",
        "Underground",
        "Offgrid",
        "Anomaly",
        "Specter",
        "Oracle",
        "Watcher",
        "Sentinel",
        "Vigil",
        "Protocol",
        "Archive",
      ],
      suffixes: [
        "Pill",
        "Seeker",
        "Watcher",
        "Rabbit",
        "Node",
        "Signal",
        "Pattern",
        "Theory",
        "Decoder",
        "Whistle",
        "Vault",
        "Network",
        "Cartel",
        "Syndicate",
        "Council",
        "Operative",
        "Researcher",
        "Investigator",
        "Prophet",
        "Witness",
        "Survivor",
        "Insider",
        "Leak",
        "Drop",
        "Pulse",
      ],
    },
    artist: {
      prefixes: [
        "Glitch",
        "Neon",
        "Canvas",
        "Palette",
        "Studio",
        "Pixel",
        "Vector",
        "Spray",
        "Ink",
        "Clay",
        "Glass",
        "Film",
        "Light",
        "Noise",
        "Dream",
        "Fragment",
        "Collage",
        "Mosaic",
        "Prism",
        "Static",
        "Retro",
        "Analog",
        "Digital",
        "Abstract",
        "Surreal",
      ],
      suffixes: [
        "Gallery",
        "Sketch",
        "Muse",
        "Frame",
        "Pixel",
        "Studio",
        "Archive",
        "Collective",
        "Atelier",
        "Canvas",
        "Sculptor",
        "Painter",
        "Curator",
        "Visionary",
        "Composer",
        "Designer",
        "Animator",
        "Illustrator",
        "Printmaker",
        "Installation",
        "Exhibit",
        "Portfolio",
        "Manifesto",
        "Sequence",
        "Composition",
      ],
    },
    tech_bro: {
      prefixes: [
        "Founder",
        "Stealth",
        "Series",
        "Cloud",
        "Alpha",
        "Beta",
        "Scale",
        "Growth",
        "Venture",
        "Protocol",
        "Neural",
        "Quantum",
        "Crypto",
        "Hyper",
        "Turbo",
        "Meta",
        "Open",
        "Distributed",
        "Autonomous",
        "Synthetic",
        "Parallel",
        "Recursive",
        "Exponential",
        "Disruptive",
        "Visionary",
      ],
      suffixes: [
        "Bro",
        "Labs",
        "Stack",
        "Ventures",
        "Protocol",
        "Systems",
        "Dynamics",
        "Networks",
        "Capital",
        "Partners",
        "Collective",
        "Platform",
        "Engine",
        "Pipeline",
        "Framework",
        "Studio",
        "Works",
        "Foundry",
        "Guild",
        "Syndicate",
        "Operator",
        "Architect",
        "Evangelist",
        "Builder",
        "Founder",
      ],
    },
    philosopher: {
      prefixes: [
        "Existential",
        "Quiet",
        "Late",
        "Abstract",
        "Cosmic",
        "Silent",
        "Infinite",
        "Temporal",
        "Moral",
        "Rational",
        "Dialectic",
        "Metaphysical",
        "Epistemic",
        "Ontological",
        "Transcendent",
        "Contemplative",
        "Stoic",
        "Socratic",
        "Platonic",
        "Nietzschean",
        "Phenomenal",
        "Liminal",
        "Noetic",
        "Arcane",
        "Speculative",
      ],
      suffixes: [
        "Mind",
        "Thread",
        "Paradox",
        "Thinker",
        "Oracle",
        "Monk",
        "Sage",
        "Scholar",
        "Hermit",
        "Poet",
        "Dreamer",
        "Witness",
        "Seeker",
        "Observer",
        "Analyst",
        "Theorist",
        "Inquirer",
        "Mystic",
        "Critic",
        "Essayist",
        "Lecturer",
        "Discourse",
        "Treatise",
        "Manifesto",
        "Question",
      ],
    },
    troll: {
      prefixes: [
        "Bridge",
        "Grief",
        "Wild",
        "Trigger",
        "Rogue",
        "Savage",
        "Feral",
        "Toxic",
        "Spicy",
        "Unhinged",
        "Cursed",
        "Based",
        "Chaotic",
        "Malicious",
        "Playful",
        "Sinister",
        "Neon",
        "Digital",
        "Anonymous",
        "Shadow",
        "Gremlin",
        "Imp",
        "Goblin",
        "Menace",
      ],
      suffixes: [
        "Troll",
        "Gremlin",
        "Imp",
        "Agent",
        "Goblin",
        "Bandit",
        "Phantom",
        "Specter",
        "Trickster",
        "Menace",
        "Instigator",
        "Provocateur",
        "Saboteur",
        "Puppeteer",
        "Operator",
        "Ghost",
        "Rat",
        "Viper",
        "Jester",
        "Clown",
        "Demon",
        "Impulse",
        "Havoc",
        "Discord",
        "Anarchy",
      ],
    },
    politician: {
      prefixes: [
        "Senator",
        "Mayor",
        "Civic",
        "Policy",
        "Public",
        "Campaign",
        "Capitol",
        "District",
        "National",
        "Local",
        "Strategic",
        "Official",
        "Elected",
        "Parliament",
        "Assembly",
        "Delegate",
        "Minister",
        "Governor",
        "Council",
        "Bureau",
        "Platform",
        "Ballot",
        "Primary",
        "Coalition",
        "Union",
      ],
      suffixes: [
        "Whip",
        "Desk",
        "Brief",
        "Signal",
        "Agenda",
        "Office",
        "Press",
        "Corps",
        "Forum",
        "Chamber",
        "Caucus",
        "Ledger",
        "Dispatch",
        "Bulletin",
        "Statement",
        "Platform",
        "Summit",
        "Hearing",
        "Committee",
        "Council",
        "Briefing",
        "Liaison",
        "Advisor",
        "Strategist",
        "Operator",
      ],
    },
    woke: {
      prefixes: [
        "Justice",
        "Solidarity",
        "Equity",
        "Liberation",
        "Collective",
        "Radical",
        "Progress",
        "Inclusive",
        "Community",
        "Conscious",
        "Aware",
        "Activist",
        "Grassroots",
        "People",
        "Public",
        "Common",
        "Shared",
        "United",
        "Open",
        "Brave",
        "Honest",
        "Loud",
        "Clear",
        "Moral",
        "Ethical",
      ],
      suffixes: [
        "Voice",
        "Signal",
        "Forum",
        "Circle",
        "Union",
        "Front",
        "Pulse",
        "Watch",
        "Desk",
        "Brief",
        "Thread",
        "Archive",
        "Network",
        "Collective",
        "Assembly",
        "Movement",
        "Platform",
        "Dispatch",
        "Bulletin",
        "Praxis",
        "Lens",
        "Stand",
        "Cause",
        "Action",
        "Solidarity",
      ],
    },
    negacionist: {
      prefixes: [
        "Skeptic",
        "Contrarian",
        "Denial",
        "Doubt",
        "Question",
        "Reject",
        "Counter",
        "Anti",
        "Unproven",
        "Disputed",
        "Alternate",
        "Hidden",
        "Forbidden",
        "Censored",
        "Suppressed",
        "Ignored",
        "Banned",
        "Exposed",
        "Uncensored",
        "Raw",
        "Hard",
        "Cold",
        "Bitter",
        "Lone",
        "Free",
      ],
      suffixes: [
        "Truth",
        "Facts",
        "Proof",
        "Signal",
        "Report",
        "Brief",
        "Watch",
        "Desk",
        "Lens",
        "Angle",
        "Take",
        "Claim",
        "Theory",
        "Doubt",
        "Reject",
        "Counter",
        "Voice",
        "Forum",
        "Archive",
        "Dispatch",
        "Bulletin",
        "Stand",
        "Line",
        "View",
        "Read",
      ],
    },
    boomer: {
      prefixes: [
        "Back",
        "Classic",
        "Old",
        "Vintage",
        "Golden",
        "Retro",
        "Traditional",
        "Honest",
        "Plain",
        "Simple",
        "Folksy",
        "Suburban",
        "Garage",
        "Basement",
        "Porch",
        "Driveway",
        "Mailbox",
        "Barbecue",
        "Fishing",
        "Garden",
        "Hardware",
        "Sunday",
        "Morning",
        "Local",
        "Community",
      ],
      suffixes: [
        "Guard",
        "Uncle",
        "Timer",
        "Email",
        "News",
        "Dad",
        "Grandpa",
        "Neighbor",
        "Moderator",
        "Historian",
        "Patriot",
        "Citizen",
        "Voter",
        "Watcher",
        "Reporter",
        "Columnist",
        "Reviewer",
        "Collector",
        "Fixer",
        "Handyman",
        "Coach",
        "Advisor",
        "Council",
        "Chronicle",
        "Bulletin",
      ],
    },
    coach: {
      prefixes: [
        "Peak",
        "Grind",
        "Alpha",
        "Mindset",
        "Daily",
        "Rise",
        "Forge",
        "Iron",
        "Steel",
        "Turbo",
        "Hyper",
        "Max",
        "Prime",
        "Elite",
        "Victory",
        "Momentum",
        "Discipline",
        "Focus",
        "Power",
        "Impact",
        "Legacy",
        "Champion",
        "Warrior",
        "Builder",
        "Operator",
      ],
      suffixes: [
        "Coach",
        "Fuel",
        "Hustle",
        "Discipline",
        "Win",
        "Mindset",
        "Protocol",
        "System",
        "Method",
        "Blueprint",
        "Playbook",
        "Routine",
        "Program",
        "Academy",
        "Lab",
        "Camp",
        "Squad",
        "Team",
        "Leader",
        "Mentor",
        "Trainer",
        "Guide",
        "Engine",
        "Formula",
        "Standard",
      ],
    },
    detective: {
      prefixes: [
        "Noir",
        "Cold",
        "Shadow",
        "Case",
        "Private",
        "Silent",
        "Grim",
        "Urban",
        "Midnight",
        "Fog",
        "Steel",
        "Crimson",
        "Hidden",
        "Secret",
        "Unknown",
        "Missing",
        "Final",
        "Last",
        "Dark",
        "Grey",
        "Rogue",
        "Lone",
        "Sharp",
        "Keen",
        "Observant",
      ],
      suffixes: [
        "Detective",
        "File",
        "Lens",
        "Trace",
        "Clue",
        "Investigator",
        "Inspector",
        "Operative",
        "Agent",
        "Profiler",
        "Analyst",
        "Researcher",
        "Archivist",
        "Witness",
        "Tracker",
        "Scanner",
        "Observer",
        "Inquirer",
        "Examiner",
        "Spotter",
        "Coroner",
        "Reporter",
        "Sleuth",
        "Hunter",
        "Decoder",
      ],
    },
    fitness: {
      prefixes: [
        "Peak",
        "Iron",
        "Core",
        "Lift",
        "Rep",
        "Gain",
        "Strong",
        "Active",
        "Daily",
        "Fit",
        "Muscle",
        "Cardio",
        "Protein",
        "Gym",
        "Train",
        "Burn",
        "Power",
        "Lean",
        "Bulk",
        "Sweat",
        "Endure",
        "Recover",
        "Mobility",
        "Athletic",
        "Performance",
      ],
      suffixes: [
        "Gains",
        "Reps",
        "Sets",
        "Fuel",
        "Coach",
        "Lab",
        "Club",
        "Crew",
        "Mode",
        "Routine",
        "Protocol",
        "Tracker",
        "Pulse",
        "Drive",
        "Engine",
        "Form",
        "Zone",
        "Circuit",
        "Sprint",
        "Lift",
        "Core",
        "Strength",
        "Recovery",
        "Program",
        "Standard",
      ],
    },
    lifestyle: {
      prefixes: [
        "Soft",
        "Slow",
        "Daily",
        "Curated",
        "Calm",
        "Clean",
        "Minimal",
        "Cozy",
        "Bright",
        "Golden",
        "Sunday",
        "Morning",
        "Balanced",
        "Simple",
        "Modern",
        "Urban",
        "Coastal",
        "Natural",
        "Mindful",
        "Intentional",
        "Aesthetic",
        "Neutral",
        "Warm",
        "Fresh",
        "Serene",
      ],
      suffixes: [
        "Edit",
        "Journal",
        "Ritual",
        "Routine",
        "Mood",
        "Vibes",
        "Notes",
        "Diary",
        "Guide",
        "Studio",
        "Home",
        "Table",
        "Shelf",
        "Corner",
        "Lane",
        "Flow",
        "Balance",
        "Habits",
        "Moments",
        "Aesthetic",
        "Palette",
        "Muse",
        "Collective",
        "Archive",
        "Edition",
      ],
    },
    fakenews: {
      prefixes: ["Breaking", "Shocking", "Secret", "Leaked", "Insider"],
      suffixes: ["Wire", "Alert", "Report", "Dispatch", "Bulletin"],
    },
    traditional: {
      prefixes: ["Daily", "Metro", "City", "National", "Evening"],
      suffixes: ["Times", "Herald", "Gazette", "Journal", "Post"],
    },
    politics: {
      prefixes: ["Capitol", "Policy", "Campaign", "Electoral", "Parliament"],
      suffixes: ["Desk", "Watch", "Brief", "Wire", "Report"],
    },
    crime: {
      prefixes: ["Metro", "Night", "Case", "Street", "Cold"],
      suffixes: ["Watch", "Files", "Desk", "Report", "Scanner"],
    },
    sports: {
      prefixes: ["Game", "Final", "Playoff", "Rivalry", "Highlight"],
      suffixes: ["Wire", "Desk", "Report", "Central", "Zone"],
    },
    tech: {
      prefixes: ["Pixel", "Cloud", "Stack", "Byte", "Signal"],
      suffixes: ["Labs", "Works", "Hub", "Systems", "Co"],
    },
    food_and_beverages: {
      prefixes: ["Fresh", "Daily", "Craft", "Urban", "Golden"],
      suffixes: ["Kitchen", "Bites", "Brew", "Table", "Pantry"],
    },
    other: {
      prefixes: ["Official", "Prime", "Urban", "Nova", "Central"],
      suffixes: ["Co", "Hub", "Works", "Group", "Page"],
    },
  };

const SHARED_INTERESTS = [
  "timeline drama",
  "viral threads",
  "online discourse",
  "platform politics",
  "internet culture",
  "late night posting",
  "quote tweets",
  "reply chains",
  "follower counts",
  "engagement metrics",
  "algorithm rumors",
  "community beef",
  "inside jokes",
  "micro trends",
  "hot takes",
  "deep lore",
  "parasocial vibes",
  "screen time",
  "doomscrolling",
  "notifications",
];

const INTERESTS: Record<Archetype, string[]> = {
  comedian: [
    "memes",
    "ratio wars",
    "standup",
    "cats",
    "dunk tweets",
    "observational humor",
    "sketch comedy",
    "improv",
    "parody accounts",
    "reaction images",
    "copypasta",
    "shitposting",
    "roast battles",
    "comedy podcasts",
    "open mics",
    "crowd work",
    "absurdism",
    "satire news",
    "funny screenshots",
    "caption contests",
    "viral clips",
    "gif replies",
    "comedy writing",
    "pun threads",
    "bit comedy",
    "cringe humor",
    "deadpan jokes",
    "internet irony",
    "meme templates",
    ...SHARED_INTERESTS,
  ],
  journalist: [
    "breaking news",
    "fact checks",
    "threads",
    "leaks",
    "politics",
    "investigations",
    "interviews",
    "press releases",
    "court filings",
    "public records",
    "data journalism",
    "source protection",
    "editorial boards",
    "headline craft",
    "live updates",
    "foreign desks",
    "local government",
    "election coverage",
    "policy analysis",
    "media ethics",
    "watchdog reporting",
    "document dumps",
    "timeline reconstructions",
    "whistleblowers",
    "newsletters",
    "morning briefings",
    "beat reporting",
    "on background chats",
    "corrections desks",
    "bylines",
    ...SHARED_INTERESTS,
  ],
  conspiracy: [
    "hidden patterns",
    "algorithms",
    "signal drops",
    "midnight radio",
    "symbols",
    "secret societies",
    "cover ups",
    "missing links",
    "anomaly hunting",
    "timeline gaps",
    "leaked documents",
    "encrypted forums",
    "occult references",
    "numerology",
    "pattern recognition",
    "surveillance lore",
    "black sites",
    "whistleblower arcs",
    "alternative history",
    "forbidden archives",
    "deep web rumors",
    "coincidences",
    "prophecy decoding",
    "map connections",
    "red string boards",
    "classified files",
    "strange broadcasts",
    "unmarked vans",
    "energy harvesting",
    "simulation theory",
    ...SHARED_INTERESTS,
  ],
  artist: [
    "glitch art",
    "exhibitions",
    "color theory",
    "NFTs",
    "sketches",
    "digital collage",
    "pixel sprites",
    "generative art",
    "zines",
    "murals",
    "sculpture",
    "photography",
    "film grain",
    "lighting studies",
    "composition",
    "art history",
    "studio visits",
    "gallery openings",
    "artist statements",
    "mixed media",
    "installation art",
    "concept sketches",
    "palette swaps",
    "fan art",
    "process videos",
    "creative blocks",
    "reference boards",
    "texture packs",
    "retro aesthetics",
    "experimental tools",
    ...SHARED_INTERESTS,
  ],
  tech_bro: [
    "startups",
    "AI",
    "fundraising",
    "productivity",
    "SaaS",
    "pitch decks",
    "YC applications",
    "growth loops",
    "PLG motion",
    "founder mode",
    "10x engineers",
    "cloud infra",
    "open source",
    "dev tools",
    "automation",
    "LLM wrappers",
    "token launches",
    "cap tables",
    "burn rate",
    "ARR milestones",
    "product launches",
    "hackathons",
    "tech twitter",
    "build in public",
    "founder podcasts",
    "angel investing",
    "venture memos",
    "API economy",
    "no code stacks",
    "future of work",
    ...SHARED_INTERESTS,
  ],
  philosopher: [
    "consciousness",
    "ethics",
    "existentialism",
    "long posts",
    "questions",
    "free will",
    "moral dilemmas",
    "metaphysics",
    "epistemology",
    "phenomenology",
    "stoicism",
    "nihilism",
    "absurdism",
    "virtue ethics",
    "thought experiments",
    "language games",
    "human condition",
    "meaning making",
    "identity",
    "time and memory",
    "beauty and truth",
    "social contracts",
    "utopia design",
    "philosophy of mind",
    "ancient texts",
    "modern thinkers",
    "slow reading",
    "dialogues",
    "paradoxes",
    "quiet contemplation",
    ...SHARED_INTERESTS,
  ],
  troll: [
    "drama",
    "hot takes",
    "bait",
    "subtlety",
    "flame wars",
    "bad faith",
    "ironic posting",
    "concern trolling",
    "sea lioning",
    "quote tweet bait",
    "ratio attempts",
    "inside jokes",
    "fake sincerity",
    "thread hijacks",
    "meme warfare",
    "trigger phrases",
    "platform rules",
    "ban evasion lore",
    "anonymous accounts",
    "sock puppets",
    "outrage cycles",
    "misdirection",
    "confusion posting",
    "ambiguity",
    "low effort bait",
    "high effort bait",
    "meta trolling",
    "audience testing",
    ...SHARED_INTERESTS,
  ],
  politician: [
    "policy debates",
    "polling",
    "campaign ads",
    "press conferences",
    "coalition building",
    "legislation",
    "scandals",
    "approval ratings",
    "talking points",
    "spin rooms",
    "fundraising",
    "town halls",
    "party politics",
    "election cycles",
    "media tours",
    "public statements",
    "committee hearings",
    "diplomacy",
    "budget fights",
    "messaging strategy",
    "opposition research",
    "grassroots organizing",
    "debate prep",
    "policy papers",
    "public opinion",
    "lobbying",
    "caucus drama",
    "photo ops",
    "sound bites",
    "legacy building",
    ...SHARED_INTERESTS,
  ],
  woke: [
    "social justice",
    "equity",
    "inclusion",
    "community care",
    "mutual aid",
    "protest culture",
    "allyship",
    "intersectionality",
    "language policing",
    "call outs",
    "accountability",
    "safe spaces",
    "representation",
    "decolonizing",
    "privilege checks",
    "solidarity",
    "liberation",
    "public education",
    "grassroots movements",
    "ethical consumption",
    "climate justice",
    "labor rights",
    "housing justice",
    "mutual support",
    "community organizing",
    "public discourse",
    "media literacy",
    "institutional critique",
    "collective action",
    "moral clarity",
    ...SHARED_INTERESTS,
  ],
  negacionist: [
    "debunking",
    "skepticism",
    "contrarian takes",
    "hidden agendas",
    "media distrust",
    "alternative facts",
    "censorship claims",
    "mainstream rejection",
    "whistleblower lore",
    "cover ups",
    "official narratives",
    "fact checking wars",
    "source skepticism",
    "institutional doubt",
    "historical revision",
    "science denial",
    "expert distrust",
    "free speech fights",
    "platform bans",
    "shadow banning",
    "deep state lore",
    "gatekeeping",
    "narrative control",
    "forbidden topics",
    "truth seeking",
    "debate bait",
    "contrarian media",
    "public doubt",
    "institutional critique",
    "anti consensus",
    ...SHARED_INTERESTS,
  ],
  boomer: [
    "email chains",
    "local news",
    "classic rock",
    "weather",
    "hoaxes",
    "Facebook groups",
    "yard sales",
    "hardware stores",
    "golf tips",
    "fishing stories",
    "grilling",
    "home repair",
    "tax complaints",
    "school nostalgia",
    "handwritten letters",
    "printed newspapers",
    "TV news anchors",
    "church bulletin",
    "community board",
    "block parties",
    "HOA drama",
    "medication ads",
    "daytime TV",
    "talk radio",
    "patriotism",
    "kids these days",
    "phone calls",
    "family photos",
    "minivan culture",
    "coupon clipping",
    ...SHARED_INTERESTS,
  ],
  coach: [
    "motivation",
    "habits",
    "fitness",
    "mindset",
    "5am routines",
    "cold plunges",
    "meal prep",
    "goal setting",
    "accountability",
    "journaling",
    "visualization",
    "discipline",
    "morning pages",
    "self improvement",
    "leadership",
    "team culture",
    "performance metrics",
    "habit stacking",
    "no excuses",
    "growth mindset",
    "resilience",
    "focus blocks",
    "weekly reviews",
    "personal branding",
    "confidence",
    "public speaking",
    "networking",
    "success stories",
    "quotes",
    "life hacks",
    ...SHARED_INTERESTS,
  ],
  detective: [
    "true crime",
    "clues",
    "cold cases",
    "interviews",
    "timelines",
    "missing persons",
    "forensics",
    "witness statements",
    "crime scenes",
    "autopsy reports",
    "motive analysis",
    "alibi checks",
    "surveillance footage",
    "police scanners",
    "case files",
    "serial patterns",
    "geographic profiling",
    "court transcripts",
    "unsolved mysteries",
    "investigative podcasts",
    "detective novels",
    "noir films",
    "interrogation tactics",
    "red herrings",
    "chain of custody",
    "DNA evidence",
    "anonymous tips",
    "case reconstructions",
    "crime maps",
    "final interviews",
    ...SHARED_INTERESTS,
  ],
  fitness: [
    "gym culture",
    "strength training",
    "cardio",
    "macros",
    "protein",
    "supplements",
    "PR tracking",
    "leg day",
    "mobility work",
    "recovery",
    "sleep optimization",
    "workout splits",
    "home gyms",
    "running clubs",
    "HIIT",
    "body recomposition",
    "lifting form",
    "gym motivation",
    "fitness challenges",
    "transformation posts",
    "athleisure",
    "sports nutrition",
    "cold plunges",
    "step counts",
    "wearable stats",
    "training logs",
    "personal records",
    "coach tips",
    "active lifestyle",
    "discipline culture",
    ...SHARED_INTERESTS,
  ],
  lifestyle: [
    "morning routines",
    "home decor",
    "meal prep",
    "skincare",
    "wellness",
    "journaling",
    "coffee rituals",
    "capsule wardrobes",
    "travel diaries",
    "farmers markets",
    "seasonal living",
    "digital detox",
    "self care",
    "mindful living",
    "aesthetic feeds",
    "book nooks",
    "candle culture",
    "matcha",
    "pilates",
    "yoga",
    "clean eating",
    "weekend reset",
    "home organization",
    "soft minimalism",
    "slow living",
    "intentional habits",
    "mood boards",
    "curated playlists",
    "Sunday rituals",
    "calm productivity",
    ...SHARED_INTERESTS,
  ],
  fakenews: [
    "clickbait",
    "outrage cycles",
    "hoaxes",
    "viral rumors",
    "tabloid drama",
    "conspiracy threads",
    ...SHARED_INTERESTS,
  ],
  traditional: [
    "headlines",
    "press briefings",
    "editorials",
    "wire reports",
    "local news",
    "investigative pieces",
    ...SHARED_INTERESTS,
  ],
  politics: [
    "elections",
    "policy fights",
    "campaign drama",
    "polling",
    "debates",
    "partisan takes",
    ...SHARED_INTERESTS,
  ],
  crime: [
    "cold cases",
    "court updates",
    "police reports",
    "true crime",
    "investigations",
    "missing persons",
    ...SHARED_INTERESTS,
  ],
  sports: [
    "game recaps",
    "trade rumors",
    "highlights",
    "fantasy leagues",
    "rivalries",
    "playoff chaos",
    ...SHARED_INTERESTS,
  ],
  tech: [
    "product launches",
    "startup culture",
    "AI hype",
    "gadget reviews",
    "developer tools",
    "SaaS drama",
    ...SHARED_INTERESTS,
  ],
  food_and_beverages: [
    "new menus",
    "coffee culture",
    "craft drinks",
    "restaurant openings",
    "recipe drops",
    "snack reviews",
    ...SHARED_INTERESTS,
  ],
  other: [
    "brand updates",
    "community posts",
    "announcements",
    "customer stories",
    "behind the scenes",
    ...SHARED_INTERESTS,
  ],
};

const TRAIT_KEYS: (keyof Traits)[] = [
  "humor",
  "aggression",
  "troll",
  "woke",
  "negacionist",
  "radical",
];

const TRAIT_BIAS: Record<Archetype, Partial<Traits>> = {
  comedian: { humor: 9, troll: 6, radical: 4 },
  journalist: { negacionist: 4, woke: 5, radical: 4 },
  conspiracy: { negacionist: 9, troll: 7, radical: 6 },
  artist: { woke: 6, radical: 7, humor: 5 },
  tech_bro: { radical: 8, aggression: 5, negacionist: 4 },
  philosopher: { woke: 6, radical: 7, humor: 3 },
  troll: { troll: 10, aggression: 8, negacionist: 5 },
  boomer: { aggression: 4, negacionist: 6, woke: 2 },
  coach: { radical: 9, aggression: 6, woke: 4 },
  detective: { negacionist: 4, aggression: 5, humor: 3 },
  politician: { radical: 8, aggression: 6, negacionist: 5 },
  woke: { woke: 10, radical: 7, aggression: 3 },
  negacionist: { negacionist: 10, troll: 6, aggression: 5 },
  fitness: { radical: 8, aggression: 5, humor: 4 },
  lifestyle: { woke: 5, radical: 4, humor: 4 },
  fakenews: { negacionist: 9, troll: 7, humor: 6 },
  traditional: { radical: 5, aggression: 4, humor: 3 },
  politics: { radical: 8, aggression: 6, negacionist: 5 },
  crime: { aggression: 7, radical: 6, humor: 3 },
  sports: { radical: 7, aggression: 5, humor: 5 },
  tech: { radical: 6, humor: 5, aggression: 4 },
  food_and_beverages: { humor: 5, woke: 4, radical: 4 },
  other: { humor: 5, radical: 4, aggression: 4 },
};

function pick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)]!;
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const KIND_INTERESTS: Partial<Record<PageKind, string[]>> = {
  artist: [
    "painting",
    "illustration",
    "gallery shows",
    "sketching",
    "color theory",
    "murals",
    "creative process",
    "studio life",
  ],
  band_page: [
    "touring",
    "vinyl",
    "new releases",
    "live gigs",
    "setlists",
    "merch drops",
    "backstage chaos",
    "music videos",
  ],
  news: ["headlines", "breaking news", "press briefings", "wire reports"],
  brand: ["product launches", "brand voice", "customer stories", "campaigns"],
  meme_page: ["memes", "shitposting", "viral clips", "ratio wars"],
};

function randomTraits(archetype: Archetype | null, kind: PageKind): Traits {
  const bias = archetype ? TRAIT_BIAS[archetype] : undefined;
  const traits = {} as Traits;

  for (const key of TRAIT_KEYS) {
    const base = bias?.[key] ?? randomInt(3, 7);
    traits[key] = Math.min(10, Math.max(0, base + randomInt(-2, 2)));
  }

  if (!archetype && kind === "artist") {
    traits.humor = Math.min(10, traits.humor + 1);
    traits.radical = Math.min(10, traits.radical + 1);
  }

  if (!archetype && kind === "band_page") {
    traits.humor = Math.min(10, traits.humor + 2);
    traits.aggression = Math.min(10, traits.aggression + 1);
  }

  return traits;
}

function randomInterests(archetype: Archetype | null, kind: PageKind): string {
  const pool =
    (archetype ? INTERESTS[archetype] : undefined) ??
    KIND_INTERESTS[kind] ??
    SHARED_INTERESTS;
  const count = randomInt(3, 6);
  const selected = new Set<string>();

  while (selected.size < count && selected.size < pool.length) {
    selected.add(pick(pool));
  }

  return Array.from(selected).join(", ");
}

const COMMON_RANDOM_GENDERS: Gender[] = ["male", "female"];

const OTHER_RANDOM_GENDERS: Gender[] = GENDERS.filter(
  (gender) => gender !== "male" && gender !== "female",
);

function randomGender(): Gender {
  if (Math.random() < 0.88) {
    return pick(COMMON_RANDOM_GENDERS);
  }

  return pick(OTHER_RANDOM_GENDERS);
}

function randomFirstName(gender: Gender): string {
  if (isMasculineGender(gender)) {
    return pick([...MALE_FIRST_NAMES, ...NEUTRAL_FIRST_NAMES]);
  }

  if (isFeminineGender(gender)) {
    return pick([...FEMALE_FIRST_NAMES, ...NEUTRAL_FIRST_NAMES]);
  }

  return pick([
    ...NEUTRAL_FIRST_NAMES,
    ...MALE_FIRST_NAMES,
    ...FEMALE_FIRST_NAMES,
  ]);
}

function randomPronouns(gender: Gender): Pronouns {
  if (Math.random() < 0.75) {
    return defaultPronounsForGender(gender);
  }

  return pick([...PRONOUNS]);
}

const NEWS_NAME_PARTS = {
  prefixes: [
    "Daily",
    "Breaking",
    "Metro",
    "City",
    "Global",
    "Live",
    "Evening",
    "Morning",
    "Capital",
    "Regional",
  ],
  suffixes: [
    "Times",
    "Herald",
    "Bulletin",
    "Report",
    "Dispatch",
    "Chronicle",
    "Wire",
    "Observer",
    "Journal",
    "Gazette",
  ],
};

const BRAND_NAME_PARTS = {
  prefixes: [
    "Official",
    "Prime",
    "Nova",
    "Pixel",
    "Hyper",
    "Core",
    "Atlas",
    "Summit",
    "Vertex",
    "Echo",
  ],
  suffixes: [
    "Media",
    "Labs",
    "Studio",
    "HQ",
    "Digital",
    "Systems",
    "Group",
    "Network",
    "Hub",
    "Works",
  ],
};

const COMPANY_NAME_PARTS = {
  prefixes: [
    "Northstar",
    "Summit",
    "Harbor",
    "Pioneer",
    "Global",
    "Metro",
    "Atlas",
    "Vertex",
    "Horizon",
    "Crown",
  ],
  suffixes: [
    "Industries",
    "Partners",
    "Consulting",
    "Holdings",
    "Enterprises",
    "Solutions",
    "Services",
    "Group",
    "Corp",
    "Co",
  ],
};

const BAND_NAME_PARTS = {
  prefixes: [
    "Neon",
    "Electric",
    "Midnight",
    "Silver",
    "Velvet",
    "Static",
    "Golden",
    "Crimson",
    "Phantom",
    "Solar",
  ],
  suffixes: [
    "Wolves",
    "Echoes",
    "Parade",
    "Syndicate",
    "Collective",
    "Riders",
    "Signals",
    "Reverb",
    "Circuit",
    "Horizon",
  ],
};

function randomNameForKind(
  kind: PageKind,
  archetype: Archetype,
  gender: Gender,
): string {
  if (kind === "person" || kind === "artist") {
    const first = randomFirstName(gender);
    const last = pick(LAST_NAMES);

    if (Math.random() < 0.92) {
      return `${first} ${last}`;
    }

    return `${first} ${pick(LAST_NAMES)} ${last}`;
  }

  if (kind === "news") {
    return `${pick(NEWS_NAME_PARTS.prefixes)} ${pick(NEWS_NAME_PARTS.suffixes)}`;
  }

  if (kind === "brand") {
    return `${pick(BRAND_NAME_PARTS.prefixes)} ${pick(BRAND_NAME_PARTS.suffixes)}`;
  }

  if (kind === "band_page") {
    const patterns = [
      () => `The ${pick(BAND_NAME_PARTS.prefixes)} ${pick(BAND_NAME_PARTS.suffixes)}`,
      () => `${pick(BAND_NAME_PARTS.prefixes)} ${pick(BAND_NAME_PARTS.suffixes)}`,
      () => `${pick(BAND_NAME_PARTS.prefixes)} & The ${pick(BAND_NAME_PARTS.suffixes)}`,
    ];
    return pick(patterns)();
  }

  if (kind === "meme_page" && archetype) {
    const parts = NAME_PARTS[archetype];
    const prefix = pick(parts.prefixes);
    const suffix = pick(parts.suffixes);
    const patterns = [
      () => `${prefix} ${suffix}`,
      () => `${prefix} Memes`,
      () => `${suffix} Posting`,
      () => `Cursed ${suffix}`,
      () => `${prefix} Shitposting`,
    ];
    return pick(patterns)();
  }

  return `${pick(BRAND_NAME_PARTS.prefixes)} ${pick(BRAND_NAME_PARTS.suffixes)}`;
}

const NON_IDENTITY_PAGE_KINDS = PAGE_KINDS.filter(
  (kind) => !profileKindUsesIdentity(kind),
);

function randomPageKind(): PageKind {
  if (Math.random() < 0.68) {
    return "person";
  }

  return pick([...NON_IDENTITY_PAGE_KINDS]);
}

function randomArchetypeForKind(kind: PageKind): Archetype | null {
  if (!pageKindUsesArchetype(kind)) {
    return null;
  }

  const allowed = getArchetypesForPageKind(kind);

  if (!allowed || allowed.length === 0) {
    return null;
  }

  return pick([...allowed]);
}

function randomHandle(name: string): string {
  const base = slugifyHandle(name) || "player";
  return `${base}_${randomInt(10, 99)}`;
}

export type RandomPersonalityDraft = {
  name: string;
  handle: string;
  kind: PageKind;
  gender?: Gender;
  pronouns?: Pronouns;
  archetype: Archetype | null;
  traits: Traits;
  politicalSwing: PoliticalSwing;
  interests: string;
};

export function generateRandomPersonality(): RandomPersonalityDraft {
  const kind = randomPageKind();
  const archetype = randomArchetypeForKind(kind);
  const gender = profileKindUsesIdentity(kind) ? randomGender() : undefined;
  const name = randomNameForKind(
    kind,
    archetype ?? "comedian",
    gender ?? "nonbinary",
  );

  return {
    name,
    handle: randomHandle(name),
    kind,
    ...(profileKindUsesIdentity(kind) && gender
      ? { gender, pronouns: randomPronouns(gender) }
      : {}),
    archetype,
    traits: randomTraits(archetype, kind),
    politicalSwing: randomPoliticalSwing(),
    interests: randomInterests(archetype, kind),
  };
}
