import { ARCHETYPES, type Archetype } from "@/lib/personalities/archetypes";
import {
  GENDERS,
  defaultPronounsForGender,
  isFeminineGender,
  isMasculineGender,
  type Gender,
} from "@/lib/personalities/gender";
import { PRONOUNS, type Pronouns } from "@/lib/personalities/pronouns";
import { slugifyHandle } from "@/lib/personalities/validation";
import type { Traits } from "@/lib/types/personality";

const MALE_FIRST_NAMES = [
  "Marcus",
  "Leo",
  "Omar",
  "Felix",
  "Victor",
  "Amir",
  "Diego",
  "Luca",
  "Theo",
  "Ivan",
  "Miles",
  "Jonah",
  "Silas",
  "Hugo",
  "Noah",
  "Logan",
  "Ethan",
  "Adrian",
  "Julian",
  "Oscar",
  "Mateo",
  "Rafael",
  "Nico",
  "Andre",
  "Malik",
];

const FEMALE_FIRST_NAMES = [
  "Emma",
  "Luna",
  "Maya",
  "Zoe",
  "Nina",
  "Cleo",
  "Iris",
  "Ruby",
  "Jade",
  "Skye",
  "Elena",
  "Sofia",
  "Priya",
  "Hana",
  "Clara",
  "Naomi",
  "Tessa",
  "Vera",
  "Ines",
  "Amina",
  "Leila",
  "Camila",
  "Freya",
  "Isla",
  "Nadia",
];

const NEUTRAL_FIRST_NAMES = [
  "Alex",
  "Jordan",
  "Sam",
  "Riley",
  "Casey",
  "Morgan",
  "Quinn",
  "Avery",
  "Blake",
  "Drew",
  "Jamie",
  "Kai",
  "Ren",
  "Yuki",
  "Rowan",
  "Sage",
  "River",
  "Skyler",
  "Remy",
  "Ash",
];

const LAST_NAMES = [
  "Reed",
  "Shaw",
  "Blake",
  "Cross",
  "Vale",
  "Stone",
  "Fox",
  "Lane",
  "Marsh",
  "Wolf",
  "Knight",
  "Storm",
  "River",
  "Lake",
  "Brooks",
  "Hayes",
  "Cole",
  "West",
  "North",
  "Page",
  "Quinn",
  "Sato",
  "Chen",
  "Patel",
  "Silva",
  "Khan",
  "Rossi",
  "Nguyen",
  "Park",
  "Singh",
  "Morales",
  "Ortega",
  "Bauer",
  "Klein",
  "Novak",
  "Ibarra",
  "Santos",
  "Romero",
  "Fischer",
  "Weber",
  "Moreau",
  "Dupont",
  "Ali",
  "Hassan",
  "Okafor",
  "Mbeki",
  "Tanaka",
  "Yamamoto",
  "Kowalski",
  "Nowak",
];

const NAME_PARTS: Record<Archetype, { prefixes: string[]; suffixes: string[] }> =
  {
    comedian: {
      prefixes: [
        "Bit",
        "Meme",
        "Ratio",
        "Joke",
        "Punchline",
        "Dunk",
        "Roast",
        "Chaos",
        "Snark",
        "Gag",
        "Wit",
        "Clown",
        "Banter",
        "Satire",
        "Cursed",
        "Based",
        "Cringe",
        "Shitpost",
        "Viral",
        "Caption",
        "Comedy",
        "Laugh",
        "Irony",
        "Parody",
        "Sketch",
      ],
      suffixes: [
        "Bot",
        "Lord",
        "Machine",
        "Goblin",
        "Comedian",
        "King",
        "Queen",
        "Factory",
        "Wizard",
        "Gremlin",
        "Pilot",
        "Engine",
        "Merchant",
        "Bandit",
        "Saint",
        "Demon",
        "Intern",
        "Professor",
        "Captain",
        "Agent",
        "Supreme",
        "Overlord",
        "Champion",
        "Menace",
        "Legend",
      ],
    },
    journalist: {
      prefixes: [
        "Daily",
        "Breaking",
        "Wire",
        "Thread",
        "Source",
        "Front",
        "Night",
        "City",
        "Global",
        "Field",
        "Press",
        "Report",
        "Signal",
        "Dispatch",
        "Bulletin",
        "Ledger",
        "Chronicle",
        "Herald",
        "Anchor",
        "Scoop",
        "Leak",
        "Brief",
        "Desk",
        "Editor",
        "Correspondent",
      ],
      suffixes: [
        "Desk",
        "Report",
        "Herald",
        "Bulletin",
        "Scoop",
        "Wire",
        "Room",
        "Beat",
        "Post",
        "Times",
        "Observer",
        "Monitor",
        "Review",
        "Journal",
        "Network",
        "Channel",
        "Briefing",
        "Dispatch",
        "Ledger",
        "Archive",
        "Corps",
        "Bureau",
        "Press",
        "Anchor",
        "Source",
      ],
    },
    reply_guy: {
      prefixes: [
        "Actually",
        "Well",
        "Counter",
        "Context",
        "Devil",
        "Technically",
        "Correction",
        "Citation",
        "Footnote",
        "Semantics",
        "Debate",
        "Rebuttal",
        "Clause",
        "Logic",
        "Premise",
        "Objection",
        "Dissent",
        "Contrarian",
        "Pedant",
        "Quibble",
        "Nuance",
        "Reply",
        "Thread",
      ],
      suffixes: [
        "Guy",
        "Bot",
        "Advocate",
        "Pointer",
        "Nerd",
        "Scholar",
        "Lawyer",
        "Professor",
        "Analyst",
        "Reviewer",
        "Critic",
        "Debater",
        "Expert",
        "Historian",
        "Factchecker",
        "Moderator",
        "Referee",
        "Editor",
        "Consultant",
        "Witness",
        "Counsel",
        "Archivist",
        "Curator",
        "Inspector",
        "Auditor",
      ],
    },
    conspiracy: {
      prefixes: [
        "Red",
        "Truth",
        "Signal",
        "Deep",
        "Hidden",
        "Shadow",
        "Black",
        "Void",
        "Cipher",
        "Echo",
        "Static",
        "Parallax",
        "Quantum",
        "Fractal",
        "Midnight",
        "Underground",
        "Offgrid",
        "Anomaly",
        "Specter",
        "Oracle",
        "Watcher",
        "Sentinel",
        "Vigil",
        "Protocol",
        "Archive",
      ],
      suffixes: [
        "Pill",
        "Seeker",
        "Watcher",
        "Rabbit",
        "Node",
        "Signal",
        "Pattern",
        "Theory",
        "Decoder",
        "Whistle",
        "Vault",
        "Network",
        "Cartel",
        "Syndicate",
        "Council",
        "Operative",
        "Researcher",
        "Investigator",
        "Prophet",
        "Witness",
        "Survivor",
        "Insider",
        "Leak",
        "Drop",
        "Pulse",
      ],
    },
    artist: {
      prefixes: [
        "Glitch",
        "Neon",
        "Canvas",
        "Palette",
        "Studio",
        "Pixel",
        "Vector",
        "Spray",
        "Ink",
        "Clay",
        "Glass",
        "Film",
        "Light",
        "Noise",
        "Dream",
        "Fragment",
        "Collage",
        "Mosaic",
        "Prism",
        "Static",
        "Retro",
        "Analog",
        "Digital",
        "Abstract",
        "Surreal",
      ],
      suffixes: [
        "Gallery",
        "Sketch",
        "Muse",
        "Frame",
        "Pixel",
        "Studio",
        "Archive",
        "Collective",
        "Atelier",
        "Canvas",
        "Sculptor",
        "Painter",
        "Curator",
        "Visionary",
        "Composer",
        "Designer",
        "Animator",
        "Illustrator",
        "Printmaker",
        "Installation",
        "Exhibit",
        "Portfolio",
        "Manifesto",
        "Sequence",
        "Composition",
      ],
    },
    tech_bro: {
      prefixes: [
        "Founder",
        "Stealth",
        "Series",
        "Cloud",
        "Alpha",
        "Beta",
        "Scale",
        "Growth",
        "Venture",
        "Protocol",
        "Neural",
        "Quantum",
        "Crypto",
        "Hyper",
        "Turbo",
        "Meta",
        "Open",
        "Distributed",
        "Autonomous",
        "Synthetic",
        "Parallel",
        "Recursive",
        "Exponential",
        "Disruptive",
        "Visionary",
      ],
      suffixes: [
        "Bro",
        "Labs",
        "Stack",
        "Ventures",
        "Protocol",
        "Systems",
        "Dynamics",
        "Networks",
        "Capital",
        "Partners",
        "Collective",
        "Platform",
        "Engine",
        "Pipeline",
        "Framework",
        "Studio",
        "Works",
        "Foundry",
        "Guild",
        "Syndicate",
        "Operator",
        "Architect",
        "Evangelist",
        "Builder",
        "Founder",
      ],
    },
    philosopher: {
      prefixes: [
        "Existential",
        "Quiet",
        "Late",
        "Abstract",
        "Cosmic",
        "Silent",
        "Infinite",
        "Temporal",
        "Moral",
        "Rational",
        "Dialectic",
        "Metaphysical",
        "Epistemic",
        "Ontological",
        "Transcendent",
        "Contemplative",
        "Stoic",
        "Socratic",
        "Platonic",
        "Nietzschean",
        "Phenomenal",
        "Liminal",
        "Noetic",
        "Arcane",
        "Speculative",
      ],
      suffixes: [
        "Mind",
        "Thread",
        "Paradox",
        "Thinker",
        "Oracle",
        "Monk",
        "Sage",
        "Scholar",
        "Hermit",
        "Poet",
        "Dreamer",
        "Witness",
        "Seeker",
        "Observer",
        "Analyst",
        "Theorist",
        "Inquirer",
        "Mystic",
        "Critic",
        "Essayist",
        "Lecturer",
        "Discourse",
        "Treatise",
        "Manifesto",
        "Question",
      ],
    },
    troll: {
      prefixes: [
        "Chaos",
        "Bridge",
        "Grief",
        "Wild",
        "Trigger",
        "Rogue",
        "Savage",
        "Feral",
        "Toxic",
        "Spicy",
        "Unhinged",
        "Cursed",
        "Based",
        "Chaotic",
        "Malicious",
        "Playful",
        "Sinister",
        "Neon",
        "Digital",
        "Anonymous",
        "Shadow",
        "Gremlin",
        "Imp",
        "Goblin",
        "Menace",
      ],
      suffixes: [
        "Troll",
        "Gremlin",
        "Imp",
        "Agent",
        "Goblin",
        "Bandit",
        "Phantom",
        "Specter",
        "Trickster",
        "Menace",
        "Instigator",
        "Provocateur",
        "Saboteur",
        "Puppeteer",
        "Operator",
        "Ghost",
        "Rat",
        "Viper",
        "Jester",
        "Clown",
        "Demon",
        "Impulse",
        "Havoc",
        "Discord",
        "Anarchy",
      ],
    },
    fan_account: {
      prefixes: [
        "Stan",
        "Ultra",
        "Forever",
        "Mega",
        "True",
        "Super",
        "Hyper",
        "Royal",
        "Golden",
        "Sacred",
        "Eternal",
        "Obsessed",
        "Devoted",
        "Loyal",
        "Prime",
        "Alpha",
        "Omega",
        "Legend",
        "Icon",
        "Supreme",
        "Ultimate",
        "Official",
        "Verified",
        "Premium",
        "Deluxe",
      ],
      suffixes: [
        "Fan",
        "Club",
        "Hive",
        "Defense",
        "Archive",
        "Squad",
        "Army",
        "Legion",
        "Union",
        "Guild",
        "Collective",
        "Network",
        "Updates",
        "Daily",
        "Central",
        "Universe",
        "World",
        "Zone",
        "Hub",
        "Portal",
        "Source",
        "Feed",
        "Radar",
        "Watch",
        "Patrol",
      ],
    },
    boomer: {
      prefixes: [
        "Back",
        "Classic",
        "Old",
        "Vintage",
        "Golden",
        "Retro",
        "Traditional",
        "Honest",
        "Plain",
        "Simple",
        "Folksy",
        "Suburban",
        "Garage",
        "Basement",
        "Porch",
        "Driveway",
        "Mailbox",
        "Barbecue",
        "Fishing",
        "Garden",
        "Hardware",
        "Sunday",
        "Morning",
        "Local",
        "Community",
      ],
      suffixes: [
        "Guard",
        "Uncle",
        "Timer",
        "Email",
        "News",
        "Dad",
        "Grandpa",
        "Neighbor",
        "Moderator",
        "Historian",
        "Patriot",
        "Citizen",
        "Voter",
        "Watcher",
        "Reporter",
        "Columnist",
        "Reviewer",
        "Collector",
        "Fixer",
        "Handyman",
        "Coach",
        "Advisor",
        "Council",
        "Chronicle",
        "Bulletin",
      ],
    },
    poet: {
      prefixes: [
        "Midnight",
        "Velvet",
        "Broken",
        "Soft",
        "Lonely",
        "Silver",
        "Golden",
        "Fading",
        "Wandering",
        "Restless",
        "Silent",
        "Bitter",
        "Tender",
        "Haunted",
        "Distant",
        "Forgotten",
        "Hidden",
        "Burning",
        "Frozen",
        "Drifting",
        "Falling",
        "Rising",
        "Endless",
        "Fragile",
        "Infinite",
      ],
      suffixes: [
        "Verse",
        "Sonnet",
        "Lyric",
        "Echo",
        "Quill",
        "Poet",
        "Ballad",
        "Ode",
        "Elegy",
        "Hymn",
        "Stanza",
        "Metaphor",
        "Whisper",
        "Sigh",
        "Dream",
        "Shadow",
        "River",
        "Ember",
        "Horizon",
        "Mirror",
        "Garden",
        "Window",
        "Notebook",
        "Inkwell",
        "Soliloquy",
      ],
    },
    coach: {
      prefixes: [
        "Peak",
        "Grind",
        "Alpha",
        "Mindset",
        "Daily",
        "Rise",
        "Forge",
        "Iron",
        "Steel",
        "Turbo",
        "Hyper",
        "Max",
        "Prime",
        "Elite",
        "Victory",
        "Momentum",
        "Discipline",
        "Focus",
        "Power",
        "Impact",
        "Legacy",
        "Champion",
        "Warrior",
        "Builder",
        "Operator",
      ],
      suffixes: [
        "Coach",
        "Fuel",
        "Hustle",
        "Discipline",
        "Win",
        "Mindset",
        "Protocol",
        "System",
        "Method",
        "Blueprint",
        "Playbook",
        "Routine",
        "Program",
        "Academy",
        "Lab",
        "Camp",
        "Squad",
        "Team",
        "Leader",
        "Mentor",
        "Trainer",
        "Guide",
        "Engine",
        "Formula",
        "Standard",
      ],
    },
    detective: {
      prefixes: [
        "Noir",
        "Cold",
        "Shadow",
        "Case",
        "Private",
        "Silent",
        "Grim",
        "Urban",
        "Midnight",
        "Fog",
        "Steel",
        "Crimson",
        "Hidden",
        "Secret",
        "Unknown",
        "Missing",
        "Final",
        "Last",
        "Dark",
        "Grey",
        "Rogue",
        "Lone",
        "Sharp",
        "Keen",
        "Observant",
      ],
      suffixes: [
        "Detective",
        "File",
        "Lens",
        "Trace",
        "Clue",
        "Investigator",
        "Inspector",
        "Operative",
        "Agent",
        "Profiler",
        "Analyst",
        "Researcher",
        "Archivist",
        "Witness",
        "Tracker",
        "Scanner",
        "Observer",
        "Inquirer",
        "Examiner",
        "Spotter",
        "Coroner",
        "Reporter",
        "Sleuth",
        "Hunter",
        "Decoder",
      ],
    },
  };

const SHARED_INTERESTS = [
  "timeline drama",
  "viral threads",
  "online discourse",
  "platform politics",
  "internet culture",
  "late night posting",
  "quote tweets",
  "reply chains",
  "follower counts",
  "engagement metrics",
  "algorithm rumors",
  "community beef",
  "inside jokes",
  "micro trends",
  "hot takes",
  "deep lore",
  "parasocial vibes",
  "screen time",
  "doomscrolling",
  "notifications",
];

const INTERESTS: Record<Archetype, string[]> = {
  comedian: [
    "memes",
    "ratio wars",
    "standup",
    "cats",
    "dunk tweets",
    "observational humor",
    "sketch comedy",
    "improv",
    "parody accounts",
    "reaction images",
    "copypasta",
    "shitposting",
    "roast battles",
    "comedy podcasts",
    "open mics",
    "crowd work",
    "absurdism",
    "satire news",
    "funny screenshots",
    "caption contests",
    "viral clips",
    "gif replies",
    "comedy writing",
    "pun threads",
    "chaos posting",
    "bit comedy",
    "cringe humor",
    "deadpan jokes",
    "internet irony",
    "meme templates",
    ...SHARED_INTERESTS,
  ],
  journalist: [
    "breaking news",
    "fact checks",
    "threads",
    "leaks",
    "politics",
    "investigations",
    "interviews",
    "press releases",
    "court filings",
    "public records",
    "data journalism",
    "source protection",
    "editorial boards",
    "headline craft",
    "live updates",
    "foreign desks",
    "local government",
    "election coverage",
    "policy analysis",
    "media ethics",
    "watchdog reporting",
    "document dumps",
    "timeline reconstructions",
    "whistleblowers",
    "newsletters",
    "morning briefings",
    "beat reporting",
    "on background chats",
    "corrections desks",
    "bylines",
    ...SHARED_INTERESTS,
  ],
  reply_guy: [
    "debates",
    "corrections",
    "footnotes",
    "semantics",
    "discourse",
    "citation needed",
    "strawman spotting",
    "logic chains",
    "definition wars",
    "context threads",
    "quote tweet analysis",
    "minor details",
    "historical accuracy",
    "stat checking",
    "source links",
    "pedantic wins",
    "argument maps",
    "rhetorical devices",
    "fallacy hunting",
    "thread necromancy",
    "devil advocacy",
    "policy nuance",
    "comment section patrol",
    "forum debates",
    "wiki edits",
    "annotation culture",
    "clarifications",
    "counterpoints",
    "receipt keeping",
    "long replies",
    ...SHARED_INTERESTS,
  ],
  conspiracy: [
    "hidden patterns",
    "algorithms",
    "signal drops",
    "midnight radio",
    "symbols",
    "secret societies",
    "cover ups",
    "missing links",
    "anomaly hunting",
    "timeline gaps",
    "leaked documents",
    "encrypted forums",
    "occult references",
    "numerology",
    "pattern recognition",
    "surveillance lore",
    "black sites",
    "whistleblower arcs",
    "alternative history",
    "forbidden archives",
    "deep web rumors",
    "coincidences",
    "prophecy decoding",
    "map connections",
    "red string boards",
    "classified files",
    "strange broadcasts",
    "unmarked vans",
    "energy harvesting",
    "simulation theory",
    ...SHARED_INTERESTS,
  ],
  artist: [
    "glitch art",
    "exhibitions",
    "color theory",
    "NFTs",
    "sketches",
    "digital collage",
    "pixel sprites",
    "generative art",
    "zines",
    "murals",
    "sculpture",
    "photography",
    "film grain",
    "lighting studies",
    "composition",
    "art history",
    "studio visits",
    "gallery openings",
    "artist statements",
    "mixed media",
    "installation art",
    "concept sketches",
    "palette swaps",
    "fan art",
    "process videos",
    "creative blocks",
    "reference boards",
    "texture packs",
    "retro aesthetics",
    "experimental tools",
    ...SHARED_INTERESTS,
  ],
  tech_bro: [
    "startups",
    "AI",
    "fundraising",
    "productivity",
    "SaaS",
    "pitch decks",
    "YC applications",
    "growth loops",
    "PLG motion",
    "founder mode",
    "10x engineers",
    "cloud infra",
    "open source",
    "dev tools",
    "automation",
    "LLM wrappers",
    "token launches",
    "cap tables",
    "burn rate",
    "ARR milestones",
    "product launches",
    "hackathons",
    "tech twitter",
    "build in public",
    "founder podcasts",
    "angel investing",
    "venture memos",
    "API economy",
    "no code stacks",
    "future of work",
    ...SHARED_INTERESTS,
  ],
  philosopher: [
    "consciousness",
    "ethics",
    "existentialism",
    "long posts",
    "questions",
    "free will",
    "moral dilemmas",
    "metaphysics",
    "epistemology",
    "phenomenology",
    "stoicism",
    "nihilism",
    "absurdism",
    "virtue ethics",
    "thought experiments",
    "language games",
    "human condition",
    "meaning making",
    "identity",
    "time and memory",
    "beauty and truth",
    "social contracts",
    "utopia design",
    "philosophy of mind",
    "ancient texts",
    "modern thinkers",
    "slow reading",
    "dialogues",
    "paradoxes",
    "quiet contemplation",
    ...SHARED_INTERESTS,
  ],
  troll: [
    "drama",
    "hot takes",
    "bait",
    "chaos",
    "subtlety",
    "flame wars",
    "bad faith",
    "ironic posting",
    "concern trolling",
    "sea lioning",
    "quote tweet bait",
    "ratio attempts",
    "inside jokes",
    "fake sincerity",
    "thread hijacks",
    "meme warfare",
    "trigger phrases",
    "comment chaos",
    "platform rules",
    "ban evasion lore",
    "anonymous accounts",
    "sock puppets",
    "outrage cycles",
    "misdirection",
    "confusion posting",
    "ambiguity",
    "low effort bait",
    "high effort bait",
    "meta trolling",
    "audience testing",
    ...SHARED_INTERESTS,
  ],
  fan_account: [
    "fandom wars",
    "merch",
    "tour updates",
    "fan edits",
    "ships",
    "stan culture",
    "setlists",
    "comebacks",
    "lightsticks",
    "fan projects",
    "fanfiction",
    "fan cams",
    "album eras",
    "chart tracking",
    "streaming parties",
    "photocard trades",
    "concert queues",
    "meet and greets",
    "fan theories",
    "easter eggs",
    "ship debates",
    "fan art",
    "cover songs",
    "b-side tracks",
    "deluxe editions",
    "award shows",
    "red carpet looks",
    "fan accounts",
    "community polls",
    "celebrity gossip",
    ...SHARED_INTERESTS,
  ],
  boomer: [
    "email chains",
    "local news",
    "classic rock",
    "weather",
    "hoaxes",
    "Facebook groups",
    "yard sales",
    "hardware stores",
    "golf tips",
    "fishing stories",
    "grilling",
    "home repair",
    "tax complaints",
    "school nostalgia",
    "handwritten letters",
    "printed newspapers",
    "TV news anchors",
    "church bulletin",
    "community board",
    "block parties",
    "HOA drama",
    "medication ads",
    "daytime TV",
    "talk radio",
    "patriotism",
    "kids these days",
    "phone calls",
    "family photos",
    "minivan culture",
    "coupon clipping",
    ...SHARED_INTERESTS,
  ],
  poet: [
    "metaphors",
    "heartbreak",
    "sunsets",
    "typewriters",
    "cafes",
    "love letters",
    "unrequited love",
    "city rain",
    "empty rooms",
    "old photographs",
    "ocean metaphors",
    "moonlight",
    "cigarette smoke",
    "train stations",
    "late walks",
    "unsent drafts",
    "romanticism",
    "free verse",
    "spoken word",
    "open mic nights",
    "journal pages",
    "melancholy",
    "nostalgia",
    "fragments",
    "imagism",
    "symbolism",
    "confessional poetry",
    "quiet mornings",
    "language rhythm",
    "beautiful sadness",
    ...SHARED_INTERESTS,
  ],
  coach: [
    "motivation",
    "habits",
    "fitness",
    "mindset",
    "5am routines",
    "cold plunges",
    "meal prep",
    "goal setting",
    "accountability",
    "journaling",
    "visualization",
    "discipline",
    "morning pages",
    "self improvement",
    "leadership",
    "team culture",
    "performance metrics",
    "habit stacking",
    "no excuses",
    "growth mindset",
    "resilience",
    "focus blocks",
    "weekly reviews",
    "personal branding",
    "confidence",
    "public speaking",
    "networking",
    "success stories",
    "quotes",
    "life hacks",
    ...SHARED_INTERESTS,
  ],
  detective: [
    "true crime",
    "clues",
    "cold cases",
    "interviews",
    "timelines",
    "missing persons",
    "forensics",
    "witness statements",
    "crime scenes",
    "autopsy reports",
    "motive analysis",
    "alibi checks",
    "surveillance footage",
    "police scanners",
    "case files",
    "serial patterns",
    "geographic profiling",
    "court transcripts",
    "unsolved mysteries",
    "investigative podcasts",
    "detective novels",
    "noir films",
    "interrogation tactics",
    "red herrings",
    "chain of custody",
    "DNA evidence",
    "anonymous tips",
    "case reconstructions",
    "crime maps",
    "final interviews",
    ...SHARED_INTERESTS,
  ],
};

const TRAIT_KEYS: (keyof Traits)[] = [
  "humor",
  "aggression",
  "charisma",
  "curiosity",
  "chaos",
  "empathy",
];

const TRAIT_BIAS: Record<Archetype, Partial<Traits>> = {
  comedian: { humor: 9, charisma: 7, chaos: 6 },
  journalist: { curiosity: 9, charisma: 6, empathy: 5 },
  reply_guy: { aggression: 7, curiosity: 8, empathy: 2 },
  conspiracy: { curiosity: 8, chaos: 7, empathy: 3 },
  artist: { curiosity: 8, charisma: 6, empathy: 7 },
  tech_bro: { charisma: 8, aggression: 5, curiosity: 7 },
  philosopher: { curiosity: 9, empathy: 6, humor: 3 },
  troll: { chaos: 10, aggression: 8, empathy: 1 },
  fan_account: { charisma: 7, empathy: 8, chaos: 5 },
  boomer: { aggression: 4, empathy: 5, curiosity: 3 },
  poet: { empathy: 9, curiosity: 7, humor: 4 },
  coach: { charisma: 9, aggression: 6, empathy: 5 },
  detective: { curiosity: 10, empathy: 4, charisma: 5 },
};

function pick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)]!;
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomTraits(archetype: Archetype): Traits {
  const bias = TRAIT_BIAS[archetype];
  const traits = {} as Traits;

  for (const key of TRAIT_KEYS) {
    const base = bias[key] ?? randomInt(3, 7);
    traits[key] = Math.min(10, Math.max(0, base + randomInt(-2, 2)));
  }

  return traits;
}

function randomInterests(archetype: Archetype): string {
  const pool = INTERESTS[archetype];
  const count = randomInt(3, 6);
  const selected = new Set<string>();

  while (selected.size < count && selected.size < pool.length) {
    selected.add(pick(pool));
  }

  return Array.from(selected).join(", ");
}

const COMMON_RANDOM_GENDERS: Gender[] = ["male", "female"];

const OTHER_RANDOM_GENDERS: Gender[] = GENDERS.filter(
  (gender) => gender !== "male" && gender !== "female",
);

function randomGender(): Gender {
  if (Math.random() < 0.88) {
    return pick(COMMON_RANDOM_GENDERS);
  }

  return pick(OTHER_RANDOM_GENDERS);
}

function randomFirstName(gender: Gender): string {
  if (isMasculineGender(gender)) {
    return pick([...MALE_FIRST_NAMES, ...NEUTRAL_FIRST_NAMES]);
  }

  if (isFeminineGender(gender)) {
    return pick([...FEMALE_FIRST_NAMES, ...NEUTRAL_FIRST_NAMES]);
  }

  return pick([
    ...NEUTRAL_FIRST_NAMES,
    ...MALE_FIRST_NAMES,
    ...FEMALE_FIRST_NAMES,
  ]);
}

function randomPronouns(gender: Gender): Pronouns {
  if (Math.random() < 0.75) {
    return defaultPronounsForGender(gender);
  }

  return pick([...PRONOUNS]);
}

function randomName(archetype: Archetype, gender: Gender): string {
  const parts = NAME_PARTS[archetype];
  const first = randomFirstName(gender);
  const last = pick(LAST_NAMES);
  const prefix = pick(parts.prefixes);
  const suffix = pick(parts.suffixes);

  const patterns = [
    () => `${first} ${last}`,
    () => `${prefix} ${suffix}`,
    () => `${first} ${suffix}`,
    () => `${prefix} ${last}`,
    () => `${first} ${prefix}`,
    () => `${first} the ${suffix}`,
    () => `${last} ${suffix}`,
    () => `${first} ${pick(LAST_NAMES)} ${suffix}`,
  ];

  return pick(patterns)();
}

function randomHandle(name: string): string {
  const base = slugifyHandle(name) || "player";
  return `${base}_${randomInt(10, 99)}`;
}

export type RandomPersonalityDraft = {
  name: string;
  handle: string;
  gender: Gender;
  pronouns: Pronouns;
  archetype: Archetype;
  traits: Traits;
  interests: string;
};

export function generateRandomPersonality(): RandomPersonalityDraft {
  const archetype = pick([...ARCHETYPES]);
  const gender = randomGender();
  const name = randomName(archetype, gender);

  return {
    name,
    handle: randomHandle(name),
    gender,
    pronouns: randomPronouns(gender),
    archetype,
    traits: randomTraits(archetype),
    interests: randomInterests(archetype),
  };
}
